version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: sport
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5436:5432"
    networks:
      - ntw

  app:
    image: pavel780/app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8111:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sport
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - ntw
networks:
  ntw:
    driver: bridge
